### ISSUE TITLE
Is add_tag_subscription still supported?

### ISSUE THREAD

**Issue by lukechilds** [totemstech/instagram-node#109]
I'm trying to subscribe to new hashtag posts. It looks like this should be supported with `add_tag_subscription` however I always get an `APISubscriptionError`.

```
> ig.add_tag_subscription('test', 'https://requestb.in/1i1e0fi1', console.log)
undefined
> { Error: APISubscriptionError: Unable to reach callback URL "https://requestb.in/1i1e0fi1".
    at handle_error (/Users/lukechilds/Dev/laserred/projects/show-tell-instagram/node_modules/instagram-node/lib/instagram.js:242:19)
    at /Users/lukechilds/Dev/laserred/projects/show-tell-instagram/node_modules/instagram-node/lib/instagram.js:1588:16
    at IncomingMessage.<anonymous> (/Users/lukechilds/Dev/laserred/projects/show-tell-instagram/node_modules/instagram-node/lib/instagram.js:197:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 400,
  error_type: 'APISubscriptionError',
  error_message: 'Unable to reach callback URL "https://requestb.in/1i1e0fi1".',
  retry: [Function: retry] }
```

[https://requestb.in/1i1e0fi1](https://requestb.in/1i1e0fi1?inspect) never gets hit.

The subscription docs linked to in your readme have been removed: https://www.instagram.com/developer/realtime/

However this page still exists on the IG docs: https://www.instagram.com/developer/subscriptions/

Although it doesn't mention anything about tags, just users.

So is add_tag_subscription still supported? Am I doing something stupid or has Instagram dropped this support from their API?

**Comment by tuancg93** [comment]
@lukechilds did you fix this 
me too . help me

**Comment by lukechilds** [comment]
@tuancg93 sorry, no I didn't. I needed a quick solution so resorted to just polling the API and checking if the latest post had changed.

**Comment by tuancg93** [comment]
@lukechilds  yes. i didn't subcription app and page 
My error : APISubscriptionError", "error_message": "Challenge verification failed
