### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by olalonde** [totemstech/instagram-node#115]
There seems to be a problem installing this package with node 6 and npm 5:

```
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/fwk/lib/fwk.js:32:13)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/instagram-node/lib/instagram.js:22:11)
```

**Comment by olalonde** [comment]
That was a bug with npm@5
