### ISSUE TITLE
Got an error 'SyntaxError: Unexpected token O ......'.

### ISSUE THREAD

**Issue by nonelove** [totemstech/instagram-node#77]
SyntaxError: Unexpected token O
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/srv/www/heart/releases/20151202120536/node_modules/instagram-node/lib/instagram.js:192:27)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

**Comment by eugenekgn** [comment]
+1

**Comment by loveintowind** [comment]
+1

**Comment by c0nstructer** [comment]
+1

**Comment by MDrooker** [comment]
Anyone have a work-around for this?

**Comment by super-ienien** [comment]
This answer is because instagram don't respond with JSON to your request. You have to provide more details about your request if you wan't help.
